set(CAR_MODEL_CMAKE_DIR ${CMAKE_CURRENT_LIST_DIR})
set(CMAKE_MODULE_PATH ${CAR_MODEL_CMAKE_DIR})

set(CAR_MODEL "B1" CACHE STRING "Car model (A, B1, C, HINO)")
set_property(CACHE CAR_MODEL PROPERTY STRINGS A B1 C HINO)

set(CAR_MODEL_IS_A 0)
set(CAR_MODEL_IS_B1 0)
set(CAR_MODEL_IS_C 0)
set(CAR_MODEL_IS_HINO 0)

if ("${CAR_MODEL}" STREQUAL "A")
  set(CAR_MODEL_IS_A 1)
elseif ("${CAR_MODEL}" STREQUAL "B1")
  set(CAR_MODEL_IS_B1 1)
elseif ("${CAR_MODEL}" STREQUAL "C")
  set(CAR_MODEL_IS_C 1)
elseif ("${CAR_MODEL}" STREQUAL "HINO")
  set(CAR_MODEL_IS_HINO 1)
endif ()

if (NOT (CAR_MODEL_IS_A OR CAR_MODEL_IS_B1 OR CAR_MODEL_IS_C OR CAR_MODEL_IS_HINO))
  message(FATAL_ERROR "Invalid car model: ${CAR_MODEL}")
endif ()
