Header header

# x, y, ego_heading, ego_speed, yawrate

float32 ego_x
float32 ego_y
float32 ego_z
float32 ego_heading
float32 ego_speed
float32 yaw_rate

float32 ukf_ego_x
float32 ukf_ego_y
float32 ukf_ego_heading
float32 ukf_ego_speed

float32 road_id
float32 lanewidth
float32 stoptolane
bool gps_fault_flag

float32 path1_to_v_x
float32 path1_to_v_y
float32 path2_to_v_x
float32 path2_to_v_y

float32 path3_to_v_x
float32 path3_to_v_y
float32 path4_to_v_x
float32 path4_to_v_y

float32 path5_to_v_x
float32 path5_to_v_y
float32 path6_to_v_x
float32 path6_to_v_y

float32 odometry
float32 odometry_auto
