#!/bin/bash

GITCMD="git"
NULLSHA="0000000000000000000000000000000000000000"
EMPTYTREESHA="4b825dc642cb6eb9a060e54bf8d69288fbee4904"
MAXSIZE="20"
MAXBYTES=$(( $MAXSIZE * 1048576 ))
BANNED_EXTENSIONS=".pb .weights .so .a .engine"
EXIT=0
PRIVATELOGFILE="/dev/null"

newFiles=$($GITCMD diff --cached --stat --name-only --diff-filter=ACMRT)

for filename in "$newFiles"; do
    hash=$($GITCMD ls-files -s "$filename" | cut -d ' ' -f 2)
    filesize=$($GITCMD cat-file -s "${hash}")
    if [[ -z $filesize  ]]; then filesize=0; fi
    filesize_mb=$(($filesize / 1048576))

    if [ "${filesize}" -gt "${MAXBYTES}" ]; then
        echo "File $filename is greater than $MAXSIZE MB. Its size is $filesize_mb MB."
        exit 1
    fi

    for ext in ${BANNED_EXTENSIONS}; do
      if [[ "${filename}" == *"${ext}" ]]; then
        echo "Files with extension $ext not allowed. Please remove file $filename"
        exit 1
      fi
    done
done
