# Turn ROS packages into .deb

set(CPACK_PACKAGE_NAME "itriadv")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "${PACKAGE_NAME} debian package")
set(CPACK_PACKAGE_VERSION_MAJOR 1)
set(CPACK_PACKAGE_VERSION_MINOR 0)
set(CPACK_PACKAGE_VERSION_PATCH 0)
set(CPACK_STRIP_FILES TRUE)
set(CPACK_PACKAGE_VERSION "${CPACK_PACKAGE_VERSION_MAJOR}.${CPACK_PACKAGE_VERSION_MINOR}.${CPACK_PACKAGE_VERSION_PATCH}")
set(CPACK_PACKAGE_FILE_NAME "${CPACK_PACKAGE_NAME}-${CAR_MODEL}-${CPACK_PACKAGE_VERSION}-${CMAKE_SYSTEM_PROCESSOR}")
set(CPACK_GENERATOR "DEB")
set(CPACK_PACKAGE_CONTACT "icl_u300@itri.org.tw")
set(CPACK_DEBIAN_PACKAGE_MAINTAINER "icl_u300")
set(CPACK_PACKAGE_VENDOR "itri")
set(CPACK_PACKAGING_INSTALL_PREFIX ${CMAKE_INSTALL_PREFIX})

include(CPack)
