cd itriadv
catkin_make --pkg camera_grabber adv_to_server 
#control from_dspace geofence geofence_pp lidar_location_send lidarxyz2lla amathutils_lib astar_initial astar_search autoware_msgs libwaypoint_follower target_planner waypoint_maker waypoint_planner mm_tp ukf_mm virbb_pub rad_grab to_dspace trimble_gps_imu_pub vehinfo_pub veh_predictwaypoint
