#!/usr/bin/env python
"""Constants about images"""

RAW_IMAGE_WIDTH = 608
RAW_IMAGE_HEIGHT = 384

LETTERBOX_BORDER_WIDTH = (RAW_IMAGE_WIDTH - RAW_IMAGE_HEIGHT) / 2

DEEPLAB_IMAGE_WIDTH = 513
DEEPLAB_IMAGE_HEIGHT = 513
DEEPLAB_RAW_TO_DEEPLAB_SCALE = float(DEEPLAB_IMAGE_WIDTH) / RAW_IMAGE_WIDTH
DEEPLAB_MIN_Y = int(LETTERBOX_BORDER_WIDTH * DEEPLAB_RAW_TO_DEEPLAB_SCALE + 0.5)
DEEPLAB_MAX_Y = int((LETTERBOX_BORDER_WIDTH + RAW_IMAGE_HEIGHT - 1) * DEEPLAB_RAW_TO_DEEPLAB_SCALE + 0.5)
