Header header

# vehicel status

float32 motor_temperature #celsius
float32 tire_pressure
float32 air_pressure
float32 battery #%
float32 steer
float32 localization
float32 odometry
float32 speed #km/hr
float32 rotating_speed
float32 bus_stop
float32 vehicle_number
float32 gear
uint8 hand_brake
float32 steering_wheel
uint8 door
uint8 air_conditioner
float32 radar
float32 lidar
float32 camera
float32 GPS
uint8 headlight
uint8 wiper
uint8 indoor_light
uint8 gross_power
uint8 left_turn_light
uint8 right_turn_light
uint8 estop
uint8 ACC_state
float32 time
float32 driving_time
float32 mileage


# battery information
float32 gross_voltage
float32 gross_current
float32 highest_voltage
float32 highest_number
float32 lowest_volage
float32 lowest_number
float32 voltage_deviation
float32 highest_temp_location
float32 highest_temperature

# mode
uint8 mode


#emergency exit
float32 emergency_exit


