# Flag from Dspapce

int32 Dspace_Flag01
int32 Dspace_Flag02
int32 Dspace_Flag03
int32 Dspace_Flag04
int32 Dspace_Flag05
int32 Dspace_Flag06
int32 Dspace_Flag07
int32 Dspace_Flag08
int32 Dspace_Flag09
int32 Dspace_Flag10
int32 Dspace_Flag11
int32 Dspace_Flag12
int32 Dspace_Flag13
int32 Dspace_Flag14
int32 Dspace_Flag15
int32 Dspace_Flag16


# Flag from PX2

int32 PX2_Flag01
int32 PX2_Flag02
int32 PX2_Flag03
int32 PX2_Flag04
int32 PX2_Flag05
int32 PX2_Flag06
int32 PX2_Flag07
int32 PX2_Flag08
int32 PX2_Flag09
int32 PX2_Flag10
int32 PX2_Flag11
int32 PX2_Flag12
int32 PX2_Flag13
int32 PX2_Flag14
int32 PX2_Flag15
int32 PX2_Flag16
