Header header
uint16 classId
float32 distance

# absolute speed
float32 absSpeed
# speed of "'relative velocity on relative coordinate'  //
# projecting onto object-to-ego-vehicle vector"
float32 relSpeed

BoxPoint bPoint
ConvexPoint cPoint
Quaternion bOrient
TrackInfo track
uint16 fusionSourceId
CamInfo camInfo
RadarInfo radarInfo
LidarInfo lidarInfo

float32 crossProbability
uint16 facing_direction
